# Generated by Django 3.2 on 2021-04-18 09:56

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dg', '0003_alter_product_category_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', django.contrib.auth.models.UserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
